_grapheChartLine:
    path:     /ChartLine
    defaults: { _controller: MyAppGrapheBundle:Graphe:ChartLine }
    
_grapheHistogramme:
    path:     /histogramme
    defaults: { _controller: MyAppGrapheBundle:Graphe:chartHistogramme }
_graphePie:
    path:     /pie
    defaults: { _controller: MyAppGrapheBundle:Graphe:Pie }
    
livraison:
    pattern:  /livraison
    defaults: { _controller: MyAppGrapheBundle:Panier:livraison }

validation:
    pattern:  /validation
    defaults: { _controller: MyAppGrapheBundle:Panier:validation }

livraisonAdresseSuppression:
    pattern:  /livraison/adresse/suppression/{id}
    defaults: { _controller: MyAppGrapheBundle:Panier:adresseSuppression }