Cartefidelit„©:
    type: entity
    table: cartefidelit√©
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        tauxreduction:
            type: float
            nullable: false
            precision: 10
            scale: 0
            comment: ''
            column: tauxReduction
        pointfidelit„©:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            column: pointFidelit√©
        seuilachat:
            type: float
            nullable: false
            precision: 10
            scale: 0
            comment: ''
            column: seuilAchat
        etat:
            type: string
            nullable: false
            length: 20
            fixed: false
            comment: ''
    lifecycleCallbacks: {  }
