Commande:
    type: entity
    table: commande
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        numcommande:
            type: string
            nullable: false
            length: 20
            fixed: false
            comment: ''
            column: numCommande
        date:
            type: date
            nullable: false
            comment: ''
    lifecycleCallbacks: {  }
