Facture:
    type: entity
    table: facture
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        numfacture:
            type: string
            nullable: false
            length: 20
            fixed: false
            comment: ''
            column: numFacture
        datefacture:
            type: date
            nullable: false
            comment: ''
            column: dateFacture
        quantit„©:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            column: quantit√©
    lifecycleCallbacks: {  }
