Produit:
    type: entity
    table: produit
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        reference:
            type: string
            nullable: false
            length: 30
            fixed: false
            comment: ''
        designation:
            type: string
            nullable: false
            length: 30
            fixed: false
            comment: ''
        taille:
            type: float
            nullable: false
            precision: 10
            scale: 0
            comment: ''
        etat:
            type: boolean
            nullable: false
            comment: ''
        description:
            type: string
            nullable: false
            length: 30
            fixed: false
            comment: ''
        prixdachat:
            type: float
            nullable: false
            precision: 10
            scale: 0
            comment: ''
            column: prixDachat
        marque:
            type: string
            nullable: false
            length: 30
            fixed: false
            comment: ''
        prixvente:
            type: float
            nullable: false
            precision: 10
            scale: 0
            comment: ''
            column: prixVente
        quantite:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
    lifecycleCallbacks: {  }
