MyApp\GrapheBundle\Entity\Administrateur:
    type: entity
    table: administrateur
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        salaire:
            type: float
            nullable: false
            precision: 10
            scale: 0
            comment: ''
        degre:
            type: string
            nullable: false
            length: 30
            fixed: false
            comment: ''
    lifecycleCallbacks: {  }
