MyApp\GrapheBundle\Entity\Compte:
    type: entity
    table: compte
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        cin:
            type: string
            nullable: false
            length: 30
            fixed: false
            comment: ''
        nom:
            type: string
            nullable: false
            length: 30
            fixed: false
            comment: ''
        prenom:
            type: string
            nullable: false
            length: 30
            fixed: false
            comment: ''
        login:
            type: string
            nullable: false
            length: 30
            fixed: false
            comment: ''
        adress:
            type: string
            nullable: false
            length: 30
            fixed: false
            comment: ''
        numtel:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
        motdepasse:
            type: string
            nullable: false
            length: 30
            fixed: false
            comment: ''
        email:
            type: string
            nullable: false
            length: 30
            fixed: false
            comment: ''
        etat:
            type: string
            nullable: false
            length: 30
            fixed: false
            comment: ''
    lifecycleCallbacks: {  }
