MyApp\GrapheBundle\Entity\Newslettre:
    type: entity
    table: newslettre
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        date:
            type: date
            nullable: false
            comment: ''
        description:
            type: string
            nullable: false
            length: 30
            fixed: false
            comment: ''
    lifecycleCallbacks: {  }
